CREATE TABLE IF NOT EXISTS authors (
   AUTHOR_ID int NOT NULL AUTO_INCREMENT,
   AUTHOR_NAME VARCHAR(100),
   PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS books(
    BOOK_ID int NOT NULL AUTO_INCREMENT,
    BOOK_NAME CHAR(150),
    PRIMARY KEY(BOOK_ID)
);

CREATE TABLE IF NOT EXISTS authors_books(
    AUTHOR_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    FOREIGN KEY(BOOK_ID) REFERENCES books(BOOK_ID),
    FOREIGN KEY(AUTHOR_ID) REFERENCES authors(AUTHOR_ID)
)
