CREATE TABLE IF NOT EXISTS books(
    BOOK_ID int NOT NULL,
    BOOK_NAME CHAR(150),
    AUTHOR_ID INT,
    PRIMARY KEY(BOOK_ID),
    FOREIGN KEY(AUTHOR_ID) REFERENCES authors(AUTHOR_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS authors (
    AUTHOR_ID int NOT NULL,
    AUTHOR_NAME VARCHAR(100),
    PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS autors_books(
    AUTHOR_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    FOREIGN KEY(BOOK_ID) REFERENCES books(BOOK_ID),
    FOREIGN KEY(AUTHOR_ID) REFERENCES authors(AUTHOR_ID)
)
